### ISSUE TITLE
"module missing" error while trying to run the generator

### ISSUE THREAD

**Issue by bmjoshi** [t3mucommontools/GenProduction#4]
Traceback (most recent call last):
  File "python/Pythia_BQuarkFilterTwoMuon_cfi.py", line 6, in <module>
    process.load('GeneratorInterface.genFilters.customthreemufilter_cfi')
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_2_18/python/FWCore/ParameterSet/Config.py", line 583, in load
    module = __import__(moduleName)
ImportError: No module named genFilters.customthreemufilter_cfi

**Comment by cherepan** [comment]
Make sure you clone also : git clone git@github.com:T3MuAnalysisTools/GeneratorInterface.git

custom three mu filter is defined there
https://github.com/T3MuAnalysisTools/GeneratorInterface/blob/master/genFilters/python/customthreemufilter_cfi.py#L3
